import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ToastContainer } from 'react-toastify';
import { Loading, Navbar } from '@/components';
import 'react-toastify/dist/ReactToastify.css';
import { IBaseProps } from '@/interface';
import { headers } from 'next/headers';
import LoginPage from './dang-nhap/page';

const inter = Montserrat({ subsets: ['vietnamese'], style: ['normal', 'italic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  //description: 'Generated by create next app',
  icons: {
    icon: 'favicon1.jpg', // /public path
  },
};

export default function RootLayout(props: IBaseProps) {
  const headersList = headers();
  const currentPath = headersList.get('x-pathname');
  console.log('currentPath:::', currentPath);

  return (
    <html lang='en'>
      <body className={inter.className} suppressHydrationWarning={true}>
        <ToastContainer />
        <Loading></Loading>
        <AntdRegistry>
          {currentPath === '/dang-nhap' ? (
            <LoginPage />
          ) : (
            <>
              <Navbar />
              {props.children}
            </>
          )}
        </AntdRegistry>
      </body>
    </html>
  );
}
